package com.econtainer.base.controller;

import com.econtainer.base.model.PlanTemplate;
import com.econtainer.base.repository.ContainerRepository;
import com.econtainer.base.repository.PlanTemplateRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /api (after Application path)
public class MainController {
    @Autowired(required=true) // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PlanTemplateRepository templateRepository;

    @Autowired(required=true)
    private ContainerRepository containerRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewPlanTemplate () {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        PlanTemplate template = new PlanTemplate();
        template.setName("Basic Template");
        template.setPlantName("strawberry");
        PlanTemplate savedEntity = templateRepository.save(template);
        return "Saved :" + savedEntity.toString();
    }

    @GetMapping(path="/all")
    public @ResponseBody
    String getAllTemplates() {
        // This returns a JSON or XML with the users
        return templateRepository.findAll().toString();
    }

    @GetMapping(path="/containers")
    public @ResponseBody
    String getAllContainers() {
        // This returns a JSON or XML with the users
        return containerRepository.findAll().toString();
    }
}
